# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
# SPDX-FileCopyrightText: 2025 Peter Magnusosn <me@kmpm.se>
#
# SPDX-License-Identifier: CC0-1.0

version: 2

project_name: unionfees

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy


builds:
  - id: unionfees-cli
    main: ./cmd/unionfees-cli/
    binary: unionfees-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
  - id: unionfees-server
    main: ./cmd/unionfees-server/
    binary: unionfees-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

# SBOMs for the archives. requires syft
# sboms:
#   - artifacts: archive



dockers_v2:
  - # Build the server docker image
    id: unionfees
    dockerfile: contrib/docker/Dockerfile.goreleaser
    ids:
      - unionfees-server
    images:
      - "ghcr.io/kmpm/unionfees"
    tags:
      - "v{{ .Version }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Unionfees-Server"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
      
