

version = 1

[[annotations]]
path = ["Makefile", "go.*", ".gitignore"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"


[[annotations]]
path = [
    "README.md",
    "cmd/unionfees-server/assets/*.*",
    "cmd/unionfees-server/templates/*.*",
    "docs/*.*",
    "testdata/*.*"
]
SPDX-FileCopyrightText = "2025 Peter Magnusosn <me@kmpm.se>"
SPDX-License-Identifier = "MIT"
