# https://taskfile.dev

version: '3'

vars:
  OUTDIR: ./out
  GIT_VERSION:
    sh: git describe --tags --always --long --dirty
  LDFLAGS: -w -s -X 'main.appVersion={{.GIT_VERSION}}'

tasks:
  default:
    desc: "build the project"
    cmds:
      - task build
      
  outdir:
    desc: "create output directory"
    generate: [ .OUTDIR ]
    cmds:
      - mkdir -p {{ .OUTDIR }}

  tidy:
    desc: "tidy and fmt"
    cmds:
      - "go mod tidy"
      - "go fmt ./..."

  audit:
    desc: "running code checks"
    cmds:
      - go mod verify
      - go vet ./...
      - go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...


  licenses:
    desc: "generate 3rd party licenses"
    deps: [ outdir ]
    cmds:
      - go run github.com/google/go-licenses@latest report ./... --template contrib/licensing-template.tpl > {{ .OUTDIR }}/licenses.json
      - reuse lint

  no-dirty:
    desc: "check for uncommitted changes"
    cmds:
      - git diff --quiet || (echo "Git working directory is not clean" && exit 1)
      - git diff --cached --quiet || (echo "Git index is not clean" && exit 1)

  checks:
    desc: "run checks"
    deps: [  tidy, audit, no-dirty ]
    

  build:
    desc: "build the project"
    deps: [ outdir ]
    cmds:
      - go build -v -ldflags "{{ .LDFLAGS }}" -o {{ .OUTDIR }}/ ./cmd/...

  
  container:
    desc: "build container image"
    cmds:
      - docker build -t unionfees:latest -f contrib/docker/Dockerfile --build-arg VERSION={{ .GIT_VERSION }} .
      # - docker tag unionfees:latest ghcr.io/kmpm/unionfees:latest
      # - docker push ghcr.io/kmpm/unionfees:latest

  pre-commit:
    desc: "run pre-commit hooks"
    deps: [ tidy, audit, licenses]
    cmds:
      - goreleaser release --snapshot --skip=publish --clean
