# SPDX-FileCopyrightText: 2025 Peter Magnusosn <me@kmpm.se>
#
# SPDX-License-Identifier: CC0-1.0
FROM scratch
ARG TARGETPLATFORM
ENTRYPOINT ["/unionfees-server"]
ENV ADDRESS=0.0.0.0:8080
EXPOSE 8080
COPY $TARGETPLATFORM/unionfees-server /unionfees-server
